### ISSUE TITLE
补充 binding 未列出的设置项

### ISSUE THREAD

**Issue by haolian9** [LEOYoon-Tsaw/Rime_collections#12]
参考 librime 1.7.3 中[关于 binding 的实现](https://github.com/rime/librime/blob/1.7.3/src/rime/gear/key_binder.cc#L97)，目前有以下比较有用的设置项未列出：

* set_option 值为 option
* unset_option 值为 option
* select 值为 schema

由于我在各处接触到的文档大都援引自这里，所以提议作者补充下

我当初是想解决 “找到快速切换到英文输入模式” 的问题，费劲周折才在源码中看到它们！
最后通过这个 绑定 `{accept: "Control+F7", set_option: ascii_mode, when: always}` 解决

**Comment by haolian9** [comment]
上面针对的具体文档[在这里](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E5%85%AB%E5%85%B6%E5%AE%83) 的 八・4。

**Comment by LEOYoon-Tsaw** [comment]
好的，感謝提供！
