### ISSUE TITLE
中文输入法难于克服之症：难判断当前是否是输入状态而选择是否出现

### ISSUE THREAD

**Issue by ednykissyou** [LEOYoon-Tsaw/Rime_collections#4]
当你在资源管理器中，按某个字母，本意是快速找到某个文件夹或文件，可是这时输入法弹出来了，你是不是很郁闷，而英文状态，非输入状态，它就不会出现。
这样的情况在Ps等很多软件都存在，你按某个键本想快速跳到某个工具，可这时中文输入法出现了。
……
以前你没在意，从些你不觉得有点不舒坦了
……

**Comment by liolok** [comment]
建议默认英文、对不同程序/窗口分别记录输入法切换状态。
